### ISSUE TITLE
請問

### ISSUE THREAD

**Issue by ha-family** [aprotoss/capital#1]
您好，想請問一下如何在mac中執行呢？
請問我可以修改嗎？
沒有寫過python  .... 使用方式跟群益api文件的差不多嗎？

感謝回覆

**Comment by aprotoss** [comment]
Hi,  
群益API 使用的方式是windows 的 Component Object Model (COM)，印象中這技術僅能使用於windows上。若你確定API可以使用於MAC上，歡迎修改成你可使用的方式。使用方式可參考我程式中的寫法，原則上和文件中的相仿。
